<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260127212612 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE sessions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_token VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9A609D13844A19ED ON sessions (session_token)');
        $this->addSql('CREATE TABLE url_logs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip_address VARCHAR(64) DEFAULT NULL, user_agent VARCHAR(500) DEFAULT NULL, referer VARCHAR(500) DEFAULT NULL, url_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EEDB0FE481CFDAE7 ON url_logs (url_id)');
        $this->addSql('CREATE INDEX idx_url_created ON url_logs (url_id, created_at)');
        $this->addSql('CREATE TABLE urls (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, short_code VARCHAR(8) NOT NULL, original_url TEXT NOT NULL, visibility VARCHAR(255) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, custom_alias VARCHAR(8) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, click_count INT NOT NULL, session_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2A9437A117D2FE0D ON urls (short_code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2A9437A1226193FD ON urls (custom_alias)');
        $this->addSql('CREATE INDEX IDX_2A9437A1613FECDF ON urls (session_id)');
        $this->addSql('CREATE INDEX idx_short_code ON urls (short_code)');
        $this->addSql('CREATE INDEX idx_session_deleted ON urls (session_id, deleted_at)');
        $this->addSql('ALTER TABLE url_logs ADD CONSTRAINT FK_EEDB0FE481CFDAE7 FOREIGN KEY (url_id) REFERENCES urls (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE urls ADD CONSTRAINT FK_2A9437A1613FECDF FOREIGN KEY (session_id) REFERENCES sessions (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE url_logs DROP CONSTRAINT FK_EEDB0FE481CFDAE7');
        $this->addSql('ALTER TABLE urls DROP CONSTRAINT FK_2A9437A1613FECDF');
        $this->addSql('DROP TABLE sessions');
        $this->addSql('DROP TABLE url_logs');
        $this->addSql('DROP TABLE urls');
    }
}
